targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # this for @RoutePage
        generate_for:
          - lib/feature/**_page.dart
          - lib/shared/**_page.dart
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        generate_for:
          - lib/route/app_router.dart
      # configs for @AutoRouterConfig() generator ...